version: "3"

services:
  server:
    build:
      context: "./backend"
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
  client:
    build:
      context: "./frontend"
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    links:
      - "server"
